import {
  HeartPulse,
  GraduationCap,
  Bus,
  Wheat,
  Briefcase,
  Shield,
  Building2,
  Building,
  Cpu,
  Leaf,
  Smile,
  MoreHorizontal,
} from "lucide-react";

export const CATEGORIES = [
  {
    id: "healthcare",
    name: "Healthcare",
    icon: "HeartPulse",
    description: "Hospital access, appointments, medicines, health information, emergency care",
    color: "#EF4444",
    bgColor: "#FEF2F2",
    problemOptions: [
      "Finding nearby hospitals",
      "Getting appointments",
      "Long waiting times",
      "Finding medicines",
      "Accessing medical records",
      "Emergency help",
      "Mental health support",
      "Health information access",
    ],
  },
  {
    id: "education",
    name: "Education",
    icon: "GraduationCap",
    description: "Students, schools, scholarships, learning, career discovery",
    color: "#3B82F6",
    bgColor: "#EFF6FF",
    problemOptions: [
      "Scholarship discovery",
      "Quality of teaching",
      "Access to learning materials",
      "Career guidance",
      "School infrastructure",
      "Higher education access",
      "Skill development",
      "Exam preparation",
    ],
  },
  {
    id: "transport",
    name: "Transport",
    icon: "Bus",
    description: "Buses, trains, traffic, parking, routes, public mobility",
    color: "#F59E0B",
    bgColor: "#FFFBEB",
    problemOptions: [
      "Bus tracking / live location",
      "Bus availability & crowding",
      "Traffic congestion",
      "Parking availability",
      "Route planning",
      "Ticketing & passes",
      "Last-mile connectivity",
      "Train information",
    ],
  },
  {
    id: "agriculture",
    name: "Agriculture",
    icon: "Wheat",
    description: "Farmers, markets, weather, crop information, logistics",
    color: "#22C55E",
    bgColor: "#F0FDF4",
    problemOptions: [
      "Market price information",
      "Weather forecasting",
      "Crop disease identification",
      "Government scheme access",
      "Selling produce directly",
      "Equipment & loans",
      "Water & irrigation",
      "Storage & logistics",
    ],
  },
  {
    id: "jobs",
    name: "Jobs & Business",
    icon: "Briefcase",
    description: "Employment, local businesses, entrepreneurship, opportunities",
    color: "#8B5CF6",
    bgColor: "#F5F3FF",
    problemOptions: [
      "Finding local jobs",
      "Skill-matching for employment",
      "Starting a small business",
      "Business registration",
      "Access to credit / loans",
      "Finding customers",
      "Gig & freelance work",
      "Government employment schemes",
    ],
  },
  {
    id: "safety",
    name: "Safety",
    icon: "Shield",
    description: "Emergency response, public safety, disaster preparedness",
    color: "#EF4444",
    bgColor: "#FFF1F2",
    problemOptions: [
      "Emergency response speed",
      "Women's safety",
      "Road accident response",
      "Disaster preparedness",
      "Crime reporting",
      "Child safety",
      "Night safety",
      "Flood / cyclone alerts",
    ],
  },
  {
    id: "public-services",
    name: "Public Services",
    icon: "Building2",
    description: "Government services, civic issues, municipal systems",
    color: "#06B6D4",
    bgColor: "#ECFEFF",
    problemOptions: [
      "Ration card & PDS",
      "Land records & documents",
      "Birth / death certificates",
      "Pension schemes",
      "Property tax",
      "Utility connections",
      "Grievance redressal",
      "Digital government services",
    ],
  },
  {
    id: "cities",
    name: "Cities & Communities",
    icon: "Building",
    description: "Waste, water, infrastructure, neighbourhood issues",
    color: "#64748B",
    bgColor: "#F8FAFC",
    problemOptions: [
      "Garbage & waste collection",
      "Street lighting",
      "Drinking water access",
      "Road condition & potholes",
      "Stray animal management",
      "Sewage & drainage",
      "Public toilet access",
      "Park & public space maintenance",
    ],
  },
  {
    id: "technology",
    name: "AI & Technology",
    icon: "Cpu",
    description: "Useful AI and technology applications for everyday life",
    color: "#EC4899",
    bgColor: "#FDF4FF",
    problemOptions: [
      "Language & translation barriers",
      "Digital literacy",
      "Internet access in rural areas",
      "AI for local languages",
      "Smartphone access",
      "Cybersecurity & scams",
      "Digital payments",
      "Data privacy",
    ],
  },
  {
    id: "environment",
    name: "Environment",
    icon: "Leaf",
    description: "Pollution, waste management, water, sustainability",
    color: "#10B981",
    bgColor: "#ECFDF5",
    problemOptions: [
      "Air quality monitoring",
      "Water body pollution",
      "Plastic waste",
      "Industrial pollution",
      "Tree cover & deforestation",
      "Beach & coastline protection",
      "Renewable energy access",
      "Climate & heat",
    ],
  },
  {
    id: "everyday",
    name: "Everyday Life",
    icon: "Smile",
    description: "Anything else that makes everyday life harder in Tamil Nadu",
    color: "#F97316",
    bgColor: "#FFF7ED",
    problemOptions: [
      "Housing & renting",
      "Food access & quality",
      "Senior citizen support",
      "Disability & accessibility",
      "Consumer rights",
      "Cultural & language preservation",
      "Community spaces",
      "Time-wasting processes",
    ],
  },
  {
    id: "other",
    name: "Other",
    icon: "MoreHorizontal",
    description: "An idea that doesn't fit the categories above",
    color: "#94A3B8",
    bgColor: "#F1F5F9",
    problemOptions: [],
  },
] as const;

export type CategoryId = (typeof CATEGORIES)[number]["id"];

export const getCategoryById = (id: string) =>
  CATEGORIES.find((c) => c.id === id);
